### ISSUE TITLE
Setup isn't working (Ubuntu 16.04)

### ISSUE THREAD

**Issue by reyostallenberg** [KeizerDev/Rhythmbox-Chromecast#6]
Bash script gives
bash: line 2: cd: /home/username/.local/share/rhythmbox/plugins/: No such file or directory
I understand I can create this directory, but it could be tested and created from the script1

After creating the dir it gives:
bash: line 8: pip: command not found
So I have to run `sudo apt-get install python-pip`
This can be tested too

**Comment by fossfreedom** [comment]
revised instructions for Ubuntu in the README.

**Comment by KeizerDev** [comment]
@reyostallenberg 
> Bash script gives
> bash: line 2: cd: /home/username/.local/share/rhythmbox/plugins/: No such file or directory
> I understand I can create this directory, but it could be tested and created from the script1
Is now build in the script.

> bash: line 8: pip: command not found
> So I have to run sudo apt-get install python-pip
> This can be tested too
I can test it but instead I just tell the user to do that first.
